# 머신 러닝 기본 익히기

## data
- X : 0~29까지 data
- 정답 : y = 2*X + 1

In [1]:
# library import
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

## X, y 데이터 셋 준비
- X : 20matrix
- y: 1D vector

In [17]:
X = np.arange(1, 30, 5)
X = X.reshape(-1, 1)
print(X)
print(X.shape)

[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]]
(6, 1)


In [4]:
X.shape

(6,)

In [18]:
y = 2 * X + 1
y

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53]])

In [19]:
sns.regplot(x=X, y=y)

<Axes: >

### Estimator (학습기) 생성

In [31]:
model_lr = LinearRegression()
print(type(model_lr))
print(model_lr)

<class 'sklearn.linear_model._base.LinearRegression'>
LinearRegression()


### 모델 학습
- 모델 식별자.fit(train_X, train_y)

In [32]:
model_lr.fit(X, y)

LinearRegression()

### 예측하기
- 테스트 데이터로 학습된 모델에 예측 수행
- 모델 식별자 predict(test_x)
- test_x의 데이터 shape은 train_X의 차원과 동일하게 해야 함

In [33]:
model_lr.predict([[45]]) 

array([[91.]])

In [34]:
model_lr.predict([[45], [100], [200]]) 

array([[ 91.],
       [201.],
       [401.]])

In [40]:
test_d = np.array([[45], [100], [200]])
y = 2* test_d + 1
y

array([[ 91],
       [201],
       [401]])