## scikit-learn 1.2.2 version 기준

scikit-learn one-hot-encoding  적용하기

## 테이터 프레임으로 실습

In [9]:
import pandas as pd
import numpy as np

In [5]:
fruit = {"과일": ["사과", "오렌지", "수박", "딸기"], "가격":[1000, 2000, 1500, 3000]}

In [7]:
fruit_df = pd.DataFrame(fruit)
fruit_df

과일    가격
0   사과  1000
1  오렌지  2000
2   수박  1500
3   딸기  3000

In [11]:
fruit_cat = np.array(fruit_df['과일']).reshape(-1, 1)
fruit_cat

array([['사과'],
       ['오렌지'],
       ['수박'],
       ['딸기']], dtype=object)

# OneHotEncoding 하는 방법

In [12]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import csr_matrix
import numpy as np

f_ohe = OneHotEncoder(sparse_output=False)

In [13]:
# 범주와 One-Hot Encoding간 매핑 생성
enc = f_ohe.fit(fruit_cat)
enc

OneHotEncoder(sparse_output=False)

In [14]:
# 실제로 변환할 때에는 transform 사용
ohe = enc.transform(fruit_cat)

In [15]:
ohe

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [16]:
fruit_cat

array([['사과'],
       ['오렌지'],
       ['수박'],
       ['딸기']], dtype=object)

In [17]:
encoder = OneHotEncoder(sparse_output=False).fit(fruit_cat)
ohe_fruit = encoder.transform(fruit_cat)
ohe_fruit

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [18]:
encoder.categories_

[array(['딸기', '사과', '수박', '오렌지'], dtype=object)]

In [19]:
encoder.inverse_transform(ohe_fruit)

array([['사과'],
       ['오렌지'],
       ['수박'],
       ['딸기']], dtype=object)

In [20]:
fruit_ohe_df = pd.DataFrame(ohe_fruit, columns=encoder.categories_[0])
fruit_ohe_df

딸기   사과   수박  오렌지
0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  1.0
2  0.0  0.0  1.0  0.0
3  1.0  0.0  0.0  0.0

In [21]:
pd.concat([fruit_df, fruit_ohe_df], axis=1)

과일    가격   딸기   사과   수박  오렌지
0   사과  1000  0.0  1.0  0.0  0.0
1  오렌지  2000  0.0  0.0  0.0  1.0
2   수박  1500  0.0  0.0  1.0  0.0
3   딸기  3000  1.0  0.0  0.0  0.0

## one hot encoding 결과를 희소 행렬로 출력
- sparse_output=True

In [23]:
encoder = OneHotEncoder(sparse_output=True).fit(fruit_cat)
ohe_sparse_result = encoder.transform(fruit_cat)

In [25]:
print(ohe_sparse_result)

  (0, 1)	1.0
  (1, 3)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [26]:
print(type(ohe_sparse_result))

<class 'scipy.sparse._csr.csr_matrix'>


In [27]:
print(ohe_sparse_result.shape)

(4, 4)


In [28]:
print(ohe_sparse_result.toarray())

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
